name: Test

on:
  push:
    branches:
    - main
  pull_request:
jobs:
  test:
    uses: lufia/workflows/.github/workflows/go-test.yml@11481ca31250b76912caa52ca686f4cc48284f2c # v0.8.1
    with:
      os-versions: '["ubuntu-24.04", "macos-15"]'
